version: "2"
services:
   redis:
      restart: always
      image: "redis"
      ports:
         - 6379:6379

   db:
      image: postgres
      environment:
         - POSTGRES_DB=${DB_NAME}
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
         - 5432:5432
