# Generated by Django 4.2.1 on 2024-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('thingsboard', 'Thingsboard')], max_length=50)),
                ('base_url', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
    ]
