# Generated by Django 4.2.1 on 2024-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_add_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=models.CharField(max_length=1024),
        ),
    ]
