# Generated by Django 4.2.1 on 2024-07-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_integration_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='last_extraction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
