# Generated by Django 4.2.1 on 2024-07-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_integration_last_extraction_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.JSONField()),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.integration')),
            ],
        ),
    ]
